/**
 * Pure helpers that turn an event (+ its wine list) into the passport's
 * autogenerated stamp and abridged blurb - no DB or network access.
 *
 * The stamp is described as data ({motif, color, dateLabel, ...}); the member
 * page draws it as a flat single-colour SVG. The same event always produces
 * the same stamp (the colour comes from a hash of the event id), so a stamp
 * never changes under a member between visits.
 */

'use strict';

// What each stamp icon means - shown to the model so it can pick the one that
// best captures an event (the drawings themselves live in public/passport.js).
const MOTIFS = {
  grapes: 'wine in general, or a grape-variety focus',
  vineyard: 'rolling vineyards: an estate or hillside terroir (Napa, Sonoma, Tuscan hills)',
  volcano: 'volcanic terroir (Etna, Santorini, Canary Islands)',
  chateau: 'historic estates and chateaux (Bordeaux, Loire)',
  river: 'river-valley wines (Mosel, Rhine, Loire, Douro)',
  mountain: 'alpine or high-altitude wines',
  wave: 'coastal, maritime or island wines',
  palm: 'warm tropical or southern-hemisphere island feel',
  sun: 'sunny summer evenings, Mediterranean warmth, rosé',
  olive: 'Mediterranean olive-grove regions (Provence, Greece, Puglia)',
  cypress: 'Tuscany or the Italian countryside',
  pine: 'forest and cool northern regions (Oregon, Alsace)',
  leaf: 'autumn, harvest, organic or natural wine',
  flower: 'spring, floral and aromatic wines',
  barrel: 'aged, cellar, old-world or traditional wines',
  bottle: 'a bottle-focused tasting, e.g. a flight of one producer',
  hourglass: 'vertical tastings and aged vintages: the passage of time',
  bubbles: 'sparkling wine and celebrations',
  cake: 'a birthday',
  star: 'a special occasion or standout event',
  crown: 'grand cru, luxury or prestige wines',
  heart: 'romance or love',
  snow: 'winter and the holidays',
  moon: 'an evening dinner or night-time event',
  flame: 'fireside, barbecue or bold, warming reds',
  globe: 'a world tour across several countries',
  compass: 'exploration and discovery',
  question: 'a blind tasting or mystery theme',
  cheese: 'a cheese pairing',
  fish: 'a seafood pairing',
  note: 'a music or jazz night',
  book: 'an educational or masterclass event',
};
const MOTIF_IDS = Object.keys(MOTIFS);

// Used when the model isn't available. First match wins, so order matters
// (more specific first). Event-text rules are checked before wine-region rules.
const MOTIF_RULES = [
  ['cake',      /birthday|b-?day|turns? \d+/],
  ['heart',     /valentin|love|romance|date night|sweetheart|galentine/],
  ['question',  /blind|mystery|guess/],
  ['bubbles',   /champagne|prosecco|sparkling|bubbl|cava|cr[ée]mant|brut|fizz|new year|nye|toast|celebrat|anniversar/],
  ['snow',      /winter|snow|holiday|christmas|festive|fireside|cozy|cosy|mulled|december|january/],
  ['cheese',    /cheese|fromage|charcuterie|pairing/],
  ['fish',      /seafood|oyster|sushi|fish|shellfish/],
  ['note',      /jazz|music|concert|vinyl|band/],
  ['book',      /masterclass|class\b|workshop|educat|101|intro|lecture|learn/],
  ['hourglass', /vertical|library|aged|vintages?\b|decades?/],
  ['volcano',   /etna|santorini|volcan|canar|tenerife|lanzarote|pantelleria/],
  ['river',     /mosel|rhine|rheingau|loire|douro|danube|river/],
  ['chateau',   /bordeaux|ch[âa]teau|medoc|pauillac|margaux|saint-[ée]milion|pomerol|sauternes/],
  ['mountain',  /mountain|alps|alpine|ski|peak|highland|andes|altitude|dolomit|piedmont|barolo|barbaresco|swiss|austria|mendoza/],
  ['cypress',   /tuscan|toscana|chianti|brunello|montalcino|italian countryside/],
  ['olive',     /provence|puglia|sicil|greece|greek|crete|olive|c[ôo]tes? du rh[ôo]ne|languedoc|roussillon/],
  ['wave',      /coast|sea\b|ocean|harbor|harbour|island|beach|bay\b|nautical|albari[ñn]o|rias baixas|r[ií]as baixas|muscadet|santorini|greece|sancerre/],
  ['palm',      /tropic|hawaii|caribbean|south africa|stellenbosch|australia|new zealand|barossa|marlborough/],
  ['pine',      /oregon|willamette|alsace|forest|woodland|pacific northwest|washington state|mosel/],
  ['vineyard',  /vineyard|terroir|napa|sonoma|estate|hillside|paso robles|santa barbara|lodi|central coast|california|rioja|ribera|priorat/],
  ['sun',       /summer|sun\b|rose\b|ros[ée]|picnic|patio|terrace|brunch|rooftop|sunset|golden hour|mediterranean|riviera/],
  ['leaf',      /autumn|fall\b|harvest|vendange|orchard|thanksgiving|october|november|organic|natural|biodynamic/],
  ['barrel',    /barrel|oak|cellar|reserve|cave|old world|classic|tradition/],
  ['flame',     /bbq|barbecue|grill|bold reds?|fire\b/],
  ['crown',     /grand cru|grands? crus?|first growth|premier cru|prestige|luxury|icon/],
  ['moon',      /night|evening|midnight|moon|candle|dinner|black tie|speakeasy|after dark|late/],
  ['globe',     /world|around the|global|travel|journey|passport|international|continent|countr(y|ies)|tour/],
  ['flower',    /spring|bloom|garden|floral|blossom|may\b|april|easter|mother|riesling|viognier/],
  ['grapes',    /grape|vine|pinot|cabernet|chardonnay|merlot|syrah|zinfandel|malbec/],
];

// Muted, classy ink colours (all legible on ivory paper).
const PALETTE = ['#5a1827', '#2f4a3a', '#1f3a52', '#6b4a1e', '#4a2f55', '#7a3b2e', '#33474f', '#6a5a1e'];

function hashString(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Pick the stamp motif from the event's name + description (+ wine regions). */
function pickMotif(event, wines) {
  // Tiers: an explicit theme in the event's own words wins; then very specific
  // terroir (volcano/river/chateau) from the event or its wines; then everything
  // else, the event's own words before the wine list.
  const own = [event.name, event.description, event.location].filter(Boolean).join(' ').toLowerCase();
  const fromWines = (wines || []).map(w => `${w.grape} ${w.region} ${w.country}`).join(' ').toLowerCase();
  const THEME = ['cake', 'heart', 'question', 'bubbles', 'snow', 'cheese', 'fish', 'note', 'book', 'hourglass'];
  const TERROIR = ['volcano', 'river', 'chateau'];
  const first = (ids, text) => {
    for (const [motif, re] of MOTIF_RULES) if (ids.includes(motif) && re.test(text)) return motif;
    return null;
  };
  const rest = MOTIF_RULES.map(r => r[0]).filter(id => !THEME.includes(id) && !TERROIR.includes(id));
  return first(THEME, own) || first(TERROIR, `${own} ${fromWines}`) || first(rest, own) || first(rest, fromWines) || first(THEME, fromWines) || 'grapes';
}

/** Event date as e.g. "14 MAR 2026" in Pacific time (the app's one timezone). */
function pacificDateLabel(date) {
  if (!date) return '';
  const d = new Date(date);
  if (isNaN(d.getTime())) return '';
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Los_Angeles', day: 'numeric', month: 'short', year: 'numeric',
  }).formatToParts(d);
  const get = t => (parts.find(p => p.type === t) || {}).value || '';
  return `${get('day')} ${get('month').toUpperCase()} ${get('year')}`;
}

/** Short arc-text label for the stamp: the event name, trimmed to fit. */
function stampLabel(name) {
  const n = String(name || '').replace(/\s+/g, ' ').trim().toUpperCase();
  return n.length > 22 ? n.slice(0, 21).trimEnd() + '…' : n;
}

/**
 * @param {{event_id: string, name: string, event_date?: *, description?: string, location?: string}} event
 * @param {Array} [wines]
 */
function buildStamp(event, wines, art) {
  const id = String(event.event_id || event.name || '');
  return {
    motif: art && MOTIF_IDS.includes(art.motif) ? art.motif : pickMotif(event, wines),
    color: PALETTE[hashString(id) % PALETTE.length],
    label: stampLabel(event.name),
    dateLabel: pacificDateLabel(event.event_date),
    // Slight deterministic tilt so a page of stamps looks hand-placed.
    tilt: (hashString(id + 't') % 9) - 4,
    shape: 'round', // every stamp is a circle
  };
}

const MAX_BLURB = 150;

/** Strip markup/URLs/extra whitespace from free text. */
function cleanText(s) {
  return String(s || '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function listJoin(items) {
  if (items.length <= 1) return items.join('');
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

/**
 * Abridged blurb for the passport. Uses the event description when there is
 * one (whole leading sentences up to ~150 chars); otherwise composes a line
 * from the location and the wine list.
 */
function abridgeDescription(event, wines) {
  const text = cleanText(event.description);
  if (text) {
    const sentences = text.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) || [text];
    let out = '';
    for (const s of sentences) {
      const next = (out + ' ' + s.trim()).trim();
      if (next.length > MAX_BLURB && out) break;
      out = next;
      if (out.length >= MAX_BLURB * 0.6) break;
    }
    if (out.length < 90 && (wines || []).length) {
      const line = winesLine(wines);
      if (line && (out + ' ' + line).length <= MAX_BLURB + 40) out = `${out.replace(/[.!?]*$/, '.')} ${line}`;
    }
    if (out.length > MAX_BLURB + 40) {
      const cut = out.slice(0, MAX_BLURB - 1);
      out = cut.slice(0, cut.lastIndexOf(' ') > 40 ? cut.lastIndexOf(' ') : cut.length).replace(/[,;:\s-]+$/, '') + '…';
    }
    return out;
  }
  const w = wines || [];
  return composeFromWines(event, w);
}

function winesLine(w) {
  const places = [...new Set(w.map(x => x.region || x.country).filter(Boolean))];
  if (!places.length) return '';
  return `${w.length} wine${w.length === 1 ? '' : 's'} from ${listJoin(places.slice(0, 3))}${places.length > 3 ? ' and beyond' : ''}.`;
}

function composeFromWines(event, w) {
  const countries = [...new Set(w.map(x => x.country).filter(Boolean))];
  const parts = [];
  if (w.length) {
    parts.push(`${w.length} wine${w.length === 1 ? '' : 's'}${countries.length ? ` from ${listJoin(countries.slice(0, 4))}` : ''}`);
  }
  const where = cleanText(event.location);
  if (parts.length) return `A tasting of ${parts[0]}${where ? ` at ${where}` : ''}.`;
  return where ? `An evening of wine at ${where}.` : 'An evening of wine with the Circle.';
}

module.exports = { MOTIFS, MOTIF_IDS, pickMotif, pacificDateLabel, stampLabel, buildStamp, abridgeDescription, cleanText, MOTIF_RULES };
