/**
 * Pure helpers that turn an event (+ its wine list) into the passport's
 * autogenerated stamp and abridged blurb - no DB or network access.
 *
 * The stamp is described as data ({motif, color, dateLabel, ...}); the member
 * page draws it as a flat single-colour SVG. The same event always produces
 * the same stamp (the colour comes from a hash of the event id), so a stamp
 * never changes under a member between visits.
 */

'use strict';

// First matching rule wins, so order matters (more specific first).
const MOTIF_RULES = [
  ['heart',     /valentin|love|romance|date night|sweetheart|galentine/],
  ['bubbles',   /champagne|prosecco|sparkling|bubbl|cava|cr[ée]mant|brut|fizz|new year|nye|toast|celebrat|birthday|anniversar/],
  ['snow',      /winter|snow|holiday|christmas|festive|fireside|cozy|cosy|mulled|december|january/],
  ['sun',       /summer|sun|rose\b|ros[ée]|picnic|patio|terrace|brunch|beach|rooftop|sunset|golden hour|mediterranean|riviera/],
  ['wave',      /coast|sea|ocean|ship|sail|harbor|harbour|island|beach|bay|nautical|seafood|oyster|albari[ñn]o|santorini|greece|greek/],
  ['mountain',  /mountain|alps|alpine|ski|peak|highland|andes|hike|altitude|dolomit|piedmont|barolo|swiss|austria/],
  ['leaf',      /autumn|fall\b|harvest|vendange|orchard|thanksgiving|october|november|forest|woodland|organic|natural|biodynamic/],
  ['barrel',    /barrel|oak|cellar|aged|vertical|library|reserve|cave|vintage|old world|classic|bordeaux|rioja|tradition/],
  ['moon',      /night|evening|midnight|moon|candle|dinner|black tie|speakeasy|after dark|late/],
  ['globe',     /world|around the|global|travel|journey|passport|international|continent|country|countries|blind|tour/],
  ['flower',    /spring|bloom|garden|floral|blossom|may\b|april|easter|mother|riesling|viognier/],
  ['grapes',    /vineyard|grape|vine|terroir|napa|sonoma|tuscany|burgundy|champagne region|pinot|cabernet|chardonnay|merlot|syrah|zinfandel|malbec/],
];

// Muted, classy ink colours (all legible on ivory paper).
const PALETTE = ['#5a1827', '#2f4a3a', '#1f3a52', '#6b4a1e', '#4a2f55', '#7a3b2e', '#33474f', '#6a5a1e'];

function hashString(s) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Pick the stamp motif from the event's name + description (+ wine regions). */
function pickMotif(event, wines) {
  // The event's own words decide first; the wine list is only a tie-breaker
  // for events whose name/description say nothing.
  const own = [event.name, event.description, event.location].filter(Boolean).join(' ').toLowerCase();
  const fromWines = (wines || []).map(w => `${w.grape} ${w.region} ${w.country}`).join(' ').toLowerCase();
  for (const text of [own, fromWines]) {
    for (const [motif, re] of MOTIF_RULES) {
      if (re.test(text)) return motif;
    }
  }
  return 'grapes';
}

/** Event date as e.g. "14 MAR 2026" in Pacific time (the app's one timezone). */
function pacificDateLabel(date) {
  if (!date) return '';
  const d = new Date(date);
  if (isNaN(d.getTime())) return '';
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Los_Angeles', day: 'numeric', month: 'short', year: 'numeric',
  }).formatToParts(d);
  const get = t => (parts.find(p => p.type === t) || {}).value || '';
  return `${get('day')} ${get('month').toUpperCase()} ${get('year')}`;
}

/** Short arc-text label for the stamp: the event name, trimmed to fit. */
function stampLabel(name) {
  const n = String(name || '').replace(/\s+/g, ' ').trim().toUpperCase();
  return n.length > 22 ? n.slice(0, 21).trimEnd() + '…' : n;
}

/**
 * @param {{event_id: string, name: string, event_date?: *, description?: string, location?: string}} event
 * @param {Array} [wines]
 */
function buildStamp(event, wines) {
  const id = String(event.event_id || event.name || '');
  return {
    motif: pickMotif(event, wines),
    color: PALETTE[hashString(id) % PALETTE.length],
    label: stampLabel(event.name),
    dateLabel: pacificDateLabel(event.event_date),
    // Slight deterministic tilt so a page of stamps looks hand-placed.
    tilt: (hashString(id + 't') % 9) - 4,
    shape: ['round', 'square', 'scalloped'][hashString(id + 's') % 3],
  };
}

const MAX_BLURB = 150;

/** Strip markup/URLs/extra whitespace from free text. */
function cleanText(s) {
  return String(s || '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function listJoin(items) {
  if (items.length <= 1) return items.join('');
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

/**
 * Abridged blurb for the passport. Uses the event description when there is
 * one (whole leading sentences up to ~150 chars); otherwise composes a line
 * from the location and the wine list.
 */
function abridgeDescription(event, wines) {
  const text = cleanText(event.description);
  if (text) {
    const sentences = text.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) || [text];
    let out = '';
    for (const s of sentences) {
      const next = (out + ' ' + s.trim()).trim();
      if (next.length > MAX_BLURB && out) break;
      out = next;
      if (out.length >= MAX_BLURB * 0.6) break;
    }
    if (out.length > MAX_BLURB) {
      const cut = out.slice(0, MAX_BLURB - 1);
      out = cut.slice(0, cut.lastIndexOf(' ') > 40 ? cut.lastIndexOf(' ') : cut.length).replace(/[,;:\s-]+$/, '') + '…';
    }
    return out;
  }
  const w = wines || [];
  const countries = [...new Set(w.map(x => x.country).filter(Boolean))];
  const parts = [];
  if (w.length) {
    parts.push(`${w.length} wine${w.length === 1 ? '' : 's'}${countries.length ? ` from ${listJoin(countries.slice(0, 4))}` : ''}`);
  }
  const where = cleanText(event.location);
  if (parts.length) return `A tasting of ${parts[0]}${where ? ` at ${where}` : ''}.`;
  return where ? `An evening of wine at ${where}.` : 'An evening of wine with the Circle.';
}

module.exports = { pickMotif, pacificDateLabel, stampLabel, buildStamp, abridgeDescription, cleanText, MOTIF_RULES };
